### ISSUE TITLE
전개속도뭐냐구...

### ISSUE THREAD

**Issue by jiji-hoon96** [bubobubobo/todo-rxjs#1]
쩔어 너란남자

**Comment by bubobubobo** [comment]
아닠ㅋㅋㅋㅋㅋㅋ 혼자 놀아본건데 어떻게 보고 왔어요 ㅋㅋㅋ

**Comment by jiji-hoon96** [comment]
ㅋㅋㅋㅋㅋ 조니 즐찾이여서 그런가... 뭐하는지 뜨던데~~ 
행동력 쩔어 리스팩
저거 강의한번해줘요

docs : 조니의 Rxjs

**Comment by bubobubobo** [comment]
제가 강의하기엔 너무 아는게 없어서 오늘 지현님 강의 들어요 ㅋㅋㅋㅋ
